apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
  namespace: default
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: bobput/sf-demo-api:790a7f7be4160651695e5d13d07af41de4fee836
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_USER
              value: "root"
            - name: MONGO_PWD
              value: "example"
            - name: MONGO_URL
              value: "mongo-service.default"
            - name: MONGO_PORT
              value: "27017"
        # - name: mongo
        #   image: mongo
        #   env:
        #     - name: MONGO_INITDB_ROOT_USERNAME
        #       value: root
        #     - name: MONGO_INITDB_ROOT_PASSWORD
        #       value: example
