apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-depl
  namespace: default
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: bobput/sf-demo-ui:bf4e9821555d22168323efcd6984382d0275752f
          ports:
            - containerPort: 80
              name: ui
